### ISSUE TITLE
bios 0071

### ISSUE THREAD

**Issue by chojuanillo** [dongyubin/nuc8i5beh#1]
Hi. thank you for the great contribution. I have a problem my bios is 0071 and I can not downgrade by the f4 method of recovery of bios, nor by any other method. It works, but I have many random reboots, you could publish a version of efi compatible with version 0071. Thank you very much.

**Comment by shitouzhijun** [comment]
66 EFi support

**Comment by zt5** [comment]
升级0071就废了··· 我现在重装都过不了 不认硬盘 提示 applenvme assert failed

**Comment by zt5** [comment]
bios还不能降级

**Comment by chojuanillo** [comment]
bios 071 works correctly !! ... the restarts were due to the suspension and the apple nap
