### ISSUE TITLE
雷电转dp进不去图形界面

### ISSUE THREAD

**Issue by wondercoon** [dongyubin/nuc8i5beh#10]
clover可以进入，-v可以显示字符界面，但是进不去图形界面。快进去时就自动重启

**Comment by shallwei** [comment]
同样问题 HDMI可以正常用。
typec 接 U3219q 读条读一半就黑屏了。

**Comment by wondercoon** [comment]
搞了好久终于找到个支持雷热插拔的，可以尝试下 https://github.com/wondercoon/EFI-FOR-NUC8i5BEK-HACKINTOSH
