### ISSUE TITLE
4k显示器，只展示了2k分辨率

### ISSUE THREAD

**Issue by caoxingxing123** [dongyubin/nuc8i5beh#11]
目前启动系统后，分辨率显示异常，我用的是HDMI，在Windows下是好的！

**Comment by inorilzy** [comment]
一样，我4k60 给我显示成2k 120，hidpi 怎么都开不开。

**Comment by dongyubin** [comment]
这个好像需要打补丁
可以看看这个：[https://www.v2ex.com/t/648168](https://www.v2ex.com/t/648168)
