### ISSUE TITLE
0073 bios 貌似解决了雷电三热插拔的问题

### ISSUE THREAD

**Issue by laodouya** [dongyubin/nuc8i5beh#3]
0073的更新日志这样写的
“Fixed issue: Thunderbolt Hot-plugging doesn't work when you use
Legacy in the BIOS.”

期待楼主更新教程和配置到 0073 版本~
感谢~

**Comment by dongyubin** [comment]
主要是0073处于不完善阶段，怕出现问题，无法降级bios

**Comment by laodouya** [comment]
我用 0073 安装了 10.14.6。Type c 接显示器(应该用的是 dp 协议)，可以热插拔。

目前遇到的问题有：
1. 显示器的喇叭没法用type c或hdmi接口传输音频，整个系统没有识别出音频输入输出设备。插了个蓝牙接收器用蓝牙耳机替代。
2. Chrome 上下翻动网页时偶尔会有中间一部分区域闪烁一下。

不知道是不是个例。

**Comment by dongyubin** [comment]
我用的是主机自带的接口插耳机或者音响，尝试过typc的音频口，然而并不识别
chrome的问题并没有出现过，你可以升级一个clover，试一下

**Comment by laodouya** [comment]
不了不了……
已经当做办公电脑了，折腾不起，不是大问题。只是跟你更新一下0073确实解决了 type c 热插拔的问题
