### ISSUE TITLE
无发在Catalina使用双屏

### ISSUE THREAD

**Issue by wilsonnkwan** [dongyubin/nuc8i5beh#5]
兄弟，我尝试用你Catalina的EFI安装，成功了。但是我不能在thunderbolt/USB-C使用另外一个屏幕。一旦插进去或拔出来，系统会自动重启。有没有办法？

**Comment by wilsonnkwan** [comment]
我bios是0071，是nuc8i7BEH。但应该没有什么不同。

**Comment by ealvati** [comment]
I have the same problem (I have NUC8i5BEH) . Mojave works OK with USB-C, but not with Catalina.
I am using BIOS 0074.

**Comment by wondercoon** [comment]
> 兄弟，我尝试用你Catalina的EFI安装，成功了。但是我不能在thunderbolt/USB-C使用另外一个屏幕。一旦插进去或拔出来，系统会自动重启。有没有办法？

雷电3目前应该不支持热插拔，关机状态下插入，然后开机行不行

**Comment by ealvati** [comment]
@wondercoon , that does not work. It will still crash

**Comment by wondercoon** [comment]
搞了好久终于找到个支持雷热插拔的，可以尝试下 https://github.com/wondercoon/EFI-FOR-NUC8i5BEK-HACKINTOSH
