### ISSUE TITLE
一些配件的问题

### ISSUE THREAD

**Issue by isxiaojian** [dongyubin/nuc8i5beh#6]
在不使用拆机网卡的情况下，如何配置蓝牙无线呢？有推荐的usb网卡和usb蓝牙吗？我查了百度上的一些资料网友推荐
网卡
https://item.jd.com/100004852332.html
蓝牙
https://item.jd.com/1240372.html
能否有别的推荐呢？

**Comment by marsteel** [comment]
https://note.bobshen.com/post/nuc-catalina.html
￼￼COMFAST CF-812AC双频千兆无线网卡5.8G （Realtek芯片，有Mac驱动）
无线网络
这块USB无线网卡虽然有Mac驱动，但客服给的驱动只支持到Mojave，在Catalina下直接告诉你不能安装。 最后使用外国网友开发的USB网卡驱动 for Catalina搞定。下载和安装方法：https://github.com/chris1111/Wireless-USB-Adapter-Clover
