### ISSUE TITLE
Catalina睡眠后立刻被唤醒然后自动重启了

### ISSUE THREAD

**Issue by Ruandy** [dongyubin/nuc8i5beh#9]
wake reason：CNVW

**Comment by XieShengda** [comment]
> wake reason：CNVW

我也碰到了这个问题, 请问你解决了吗

**Comment by Ruandy** [comment]
> > wake reason：CNVW
> 
> 我也碰到了这个问题, 请问你解决了吗

并没有 换成opencore也是不行  于是决定不休眠了orz

**Comment by wondercoon** [comment]
我打了下面的补丁后好了：
636F6D2E 6170706C 65005F5F 6B65726E 656C5F5F 00     查找
6E6F742E 6170706C 65005F5F 6B65726E 656C5F5F 00     替换
fix reboot after wake from sleep                                      注释

**Comment by pro4jhu** [comment]
我也遇到同样的问题,不过我没注意是不是立即唤醒,有时候睡眠后过一段时间回来发现已经重启了
